#!/bin/bash

echo "----- [TEST] 1"
./nindex 1

echo "----- [TEST] n12"
./nindex n12

echo "----- [TEST] n12 100"
./nindex n12 100

echo "----- [TEST] n12 100 + 101"
./nindex n12 100 + 101

echo "----- [TEST] n12 100 thru 105"
./nindex n12 100 thru 105

echo "----- [TEST] n12 100 thru 105 thru 107"
./nindex n12 100 thru 105 thru 107

echo "----- [TEST] n12 100 thru 105 - 103"
./nindex n12 100 thru 105 - 103

echo "----- [TEST] 100 thru 105 - 103"
./nindex 100 thru 105 - 103

echo "----- [TEST] n12 100 thru 105 n13 1 thru 5"
./nindex n12 100 thru 105 n13 1 thru 5

exit 0
